### ISSUE TITLE
Práctica TestRail y Login

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/actividad-6-practica-de-calidad-de-testrail-con-wallet-entrevista-metztli_team#1]
[Práctica TestRail y Login.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-calidad-de-testrail-con-wallet-entrevista-metztli_team/files/9691763/Practica.TestRail.y.Login.pdf)

**Comment by javiern-778** [comment]
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
